"""Mehr felder für Charaktere

Revision ID: 7d9c9bc775d4
Revises: 
Create Date: 2025-07-24 16:11:35.159433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9c9bc775d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('species', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('background', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('alignment', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('experience_points', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('strength', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('dexterity', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('constitution', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('intelligence', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('wisdom', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('charisma', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('armor_class', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('initiative', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('speed', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('hit_points_max', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('hit_points_current', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('hit_dice', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('inspiration', sa.Boolean(), nullable=True))
    op.add_column('characters', sa.Column('proficiency_bonus', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('passive_perception', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('languages', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('image', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('biography', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'biography')
    op.drop_column('characters', 'image')
    op.drop_column('characters', 'notes')
    op.drop_column('characters', 'languages')
    op.drop_column('characters', 'passive_perception')
    op.drop_column('characters', 'proficiency_bonus')
    op.drop_column('characters', 'inspiration')
    op.drop_column('characters', 'hit_dice')
    op.drop_column('characters', 'hit_points_current')
    op.drop_column('characters', 'hit_points_max')
    op.drop_column('characters', 'speed')
    op.drop_column('characters', 'initiative')
    op.drop_column('characters', 'armor_class')
    op.drop_column('characters', 'charisma')
    op.drop_column('characters', 'wisdom')
    op.drop_column('characters', 'intelligence')
    op.drop_column('characters', 'constitution')
    op.drop_column('characters', 'dexterity')
    op.drop_column('characters', 'strength')
    op.drop_column('characters', 'experience_points')
    op.drop_column('characters', 'alignment')
    op.drop_column('characters', 'background')
    op.drop_column('characters', 'species')
    # ### end Alembic commands ###
